# Generated by Django 2.1.8 on 2021-08-20 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
