# Generated by Django 2.1.8 on 2021-08-20 09:04

from django.db import migrations, models
import django.db.models.deletion
import mainApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_remove_category_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='attachmentTranscript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=mainApp.models.path_and_renameListing, verbose_name='ListDoc')),
                ('postDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('content_type', models.CharField(default=None, max_length=500)),
                ('name', models.CharField(default=None, max_length=5000)),
            ],
            options={
                'db_table': 'attachmenttranscript',
            },
        ),
        migrations.CreateModel(
            name='theAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=500)),
                ('details', models.TextField(default=None)),
                ('moreDetails', models.TextField(default=None)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainApp.category')),
                ('images', models.ManyToManyField(to='mainApp.attachmentTranscript')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainApp.profile')),
            ],
            options={
                'db_table': 'theAdd',
            },
        ),
    ]
