# Generated by Django 2.1.8 on 2021-08-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_theadd_averagerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
