# Generated by Django 2.1.8 on 2021-09-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_auto_20210902_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='typeOfRegisteration',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
