# Generated by Django 2.1.8 on 2021-09-03 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_profile_typeofregisteration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='typeOfRegisteration',
        ),
    ]
