# Generated by Django 2.1.8 on 2021-09-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_remove_profile_typeofregisteration'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='typeOfRegisteration',
            field=models.CharField(default='Normal', max_length=500, null=True),
        ),
    ]
