# Generated by Django 2.1.8 on 2021-09-07 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_auto_20210907_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(default=None)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fromUserMainComment', to='mainApp.profile')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(default=None)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fromUser', to='mainApp.profile')),
            ],
            options={
                'db_table': 'reply',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='replies',
            field=models.ManyToManyField(to='mainApp.reply'),
        ),
        migrations.AddField(
            model_name='theadd',
            name='comments',
            field=models.ManyToManyField(to='mainApp.comment'),
        ),
    ]
