# Generated by Django 2.1.8 on 2021-09-07 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_comment_rateadd'),
    ]

    operations = [
        migrations.CreateModel(
            name='rateFromPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rateadd', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fromUserRate', to='mainApp.profile')),
            ],
            options={
                'db_table': 'rateFromPerson',
            },
        ),
        migrations.AddField(
            model_name='theadd',
            name='rateFromPersons',
            field=models.ManyToManyField(to='mainApp.rateFromPerson'),
        ),
    ]
