# Generated by Django 2.1.8 on 2021-09-07 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_auto_20210907_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratefromperson',
            name='fromUser',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='rateadd',
            new_name='rate',
        ),
        migrations.RemoveField(
            model_name='theadd',
            name='averageRate',
        ),
        migrations.RemoveField(
            model_name='theadd',
            name='rateFromPersons',
        ),
        migrations.DeleteModel(
            name='rateFromPerson',
        ),
    ]
