# Generated by Django 2.1.8 on 2021-09-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_auto_20210907_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theadd',
            name='moreDetails',
        ),
        migrations.AddField(
            model_name='profile',
            name='aboutMe',
            field=models.TextField(default=None, null=True),
        ),
    ]
