# Generated by Django 2.1.8 on 2021-09-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_auto_20210907_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='theadd',
            name='videoUrl',
            field=models.TextField(default=None, null=True),
        ),
    ]
