# Generated by Django 2.1.8 on 2021-09-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_theadd_videourl'),
    ]

    operations = [
        migrations.AddField(
            model_name='theadd',
            name='featureAddNumber',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
